name: Sync to Hugging Face hub
on:
  push:
  pull_request:
    branches:
      - master

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: Happys
          SPACE_NAME: bing
        run: |
          git clone https://$HF_USERNAME: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@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME huggingface
          git lfs install
          cd huggingface
          git config user.name Happys
          git config user.email admin@wdsj.one
          git commit -m "auto push and build"
          git push https://$HF_USERNAME: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@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main -f
